export const CREATE_DEPTO = "CREATE_DEPTO";
export const LOAD_DEPTOS_SUCCESS = "LOAD_DEPTOS_SUCCESS";

export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";

export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
